# Setup
title:               ENGL 7370
tagline:             'Introduction to Digital Humanities'
description:         'A graduate seminar offered in the Northeastern University English Department, Fall 2020'
url:                 https://f20idh.ryancordell.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ryan Cordell
  url:               https://ryancordell.org
  email:             r.cordell@northeastern.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
