# Setup
title:               Intro to Digital Humanities
tagline:             ''
description:         'A graduate seminar in the Northeastern University English Department, Fall 2020'
url:                 http://f20idh.ryancordell.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ryan Cordell
  url:               https://ryancordell.org
  email:             r.cordell@northeastern.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
